# Your project's details
PROJECT_NAME: jQuery.promises
GITHUB_CURRENT_VERSION: 1.0
GITHUB_PROJECT_URL: https://github.com/dharmafly/jquery.promises

# The style for your site (options: forest, ocean)
THEME: forest

############ Optional extras

GITHUB_ZIP_URL: https://github.com/dharmafly/jquery.promises/zipball/master
TWITTER_PROJECT_URL: https://twitter.com/dharmafly
# options: javascript, css, html5
LANG: javascript

# Add your project's scripts here to be available to any examples
SCRIPTS:
- src: https://raw.github.com/dharmafly/jquery.promises/master/image.js
- src: https://raw.github.com/dharmafly/jquery.promises/master/timer.js

REFERENCE_LINK_TEXT: "Complete documentation can be found here:"

# A quote to add at the footer of your project page
QUOTE:
  quote:  Promises are the uniquely human way of ordering the future, making it predictable and reliable to the extent that this is humanly possible
  cite: Hannah Arendt

# Your google analytics id
GA_ID: UA-34978047-2

##############

# Page names -- paths should not be updated and
# are currently hard-coded to match directory names / site categories.
# (They're here as placeholders for future work to
# allow new sections to be dynamically created)
sections:
 - path:
   name: Overview
 - path: reference
   name: Reference

###############################

# Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
